/* generated by tools/photos.sh — do not hand-edit */
const PHOTOS = [
  { src: 'photos/01.jpg', w: 1600, h: 2000 },
  { src: 'photos/02.jpg', w: 1600, h: 2000 },
  { src: 'photos/03.jpg', w: 1600, h: 2000 },
  { src: 'photos/04.jpg', w: 1600, h: 2000 },
  { src: 'photos/05.jpg', w: 1600, h: 2000 },
  { src: 'photos/06.jpg', w: 1584, h: 1980 },
];
export default PHOTOS;
