/* generated by tools/photos.sh — do not hand-edit */
const PHOTOS = [
  { src: 'photos/01.jpg', w: 1600, h: 1600 },
  { src: 'photos/02.jpg', w: 1600, h: 2400 },
  { src: 'photos/03.jpg', w: 1428, h: 1786 },
];
export default PHOTOS;
