/* generated by tools/photos.sh — do not hand-edit.
   No photos yet: drop originals in the Calabria working folder and run
   tools/photos.sh "<folder>/pictures" ../calabria — the gallery auto-appears. */
const PHOTOS = [
];
export default PHOTOS;
