#!/bin/zsh
# Product-photo pipeline: source folder -> web-ready webp set + JS manifest.
#   ./photos.sh "/path/to/pictures" ../baroque
# Emits <out>/photos/NN.jpg (max 1600px) + <out>/photos.js (src + dims).
# Re-run any time photos are added/removed — fully regenerates, order = filename sort.
set -e
SRC="$1"; OUT="$2"
[ -z "$SRC" ] || [ -z "$OUT" ] && { echo "usage: photos.sh <src-folder> <page-folder>"; exit 1; }
mkdir -p "$OUT/photos"
rm -f "$OUT/photos"/*.jpg(N)
i=0
js="/* generated by tools/photos.sh — do not hand-edit */\nconst PHOTOS = ["
for f in "$SRC"/*.(jpg|jpeg|png|JPG|JPEG|PNG|heic|HEIC)(N); do
  i=$((i+1)); n=$(printf "%02d" $i)
  ffmpeg -y -loglevel error -i "$f" -vf "scale='min(1600,iw)':-2" -q:v 3 "$OUT/photos/$n.jpg"
  wh=$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=p=0 "$OUT/photos/$n.jpg")
  w="${wh%%,*}"; h="${wh##*,}"
  js="$js\n  { src: 'photos/$n.jpg', w: $w, h: $h },"
  echo "  $n.jpg  ${w}x${h}  ($(basename $f))"
done
js="$js\n];\nexport default PHOTOS;"
print -- "$js" > "$OUT/photos.js"
echo "wrote $OUT/photos.js ($i photos)"
