/* generated by tools/photos.sh — do not hand-edit */
const PHOTOS = [
  { src: 'photos/01.jpg', w: 1600, h: 1600 },
  { src: 'photos/02.jpg', w: 1600, h: 2000 },
  { src: 'photos/03.jpg', w: 1600, h: 2000 },
  { src: 'photos/04.jpg', w: 1308, h: 1634 },
];
export default PHOTOS;
